//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awful.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Awful.Core.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Forum Selector in HTML..
        /// </summary>
        public static string ForumSelectorMissing {
            get {
                return ResourceManager.GetString("ForumSelectorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Forums Table in HTML..
        /// </summary>
        public static string ForumTableMissing {
            get {
                return ResourceManager.GetString("ForumTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you must be a registered forums member to view this page..
        /// </summary>
        public static string PaywallThreadHit {
            get {
                return ResourceManager.GetString("PaywallThreadHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must include a postId greater than 0..
        /// </summary>
        public static string PostIdMissing {
            get {
                return ResourceManager.GetString("PostIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must include either a threadId or a postId greater than 0..
        /// </summary>
        public static string ThreadAndPostIdMissing {
            get {
                return ResourceManager.GetString("ThreadAndPostIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must include a threadId greater than 0..
        /// </summary>
        public static string ThreadIdMissing {
            get {
                return ResourceManager.GetString("ThreadIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find thread list in HTML..
        /// </summary>
        public static string ThreadListMissing {
            get {
                return ResourceManager.GetString("ThreadListMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must be authenticated before using this method..
        /// </summary>
        public static string UserAuthenticationError {
            get {
                return ResourceManager.GetString("UserAuthenticationError", resourceCulture);
            }
        }
    }
}
