//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awful.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Awful.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AwfulClient failed to make a request. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AwfulClientError {
            get {
                return ResourceManager.GetString("AwfulClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find Forum Selector in HTML. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForumSelectorMissing {
            get {
                return ResourceManager.GetString("ForumSelectorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find Forums Table in HTML. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForumTableMissing {
            get {
                return ResourceManager.GetString("ForumTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry, you must be a registered forums member to view this page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PaywallThreadHit {
            get {
                return ResourceManager.GetString("PaywallThreadHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must include a postId greater than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostIdMissing {
            get {
                return ResourceManager.GetString("PostIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must include either a threadId or a postId greater than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThreadAndPostIdMissing {
            get {
                return ResourceManager.GetString("ThreadAndPostIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must include a threadId greater than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThreadIdMissing {
            get {
                return ResourceManager.GetString("ThreadIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find thread list in HTML. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThreadListMissing {
            get {
                return ResourceManager.GetString("ThreadListMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User must be authenticated before using this method. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserAuthenticationError {
            get {
                return ResourceManager.GetString("UserAuthenticationError", resourceCulture);
            }
        }
    }
}
