// <auto-generated />
using Awful.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Awful.Core.Migrations.UserAuth
{
    [DbContext(typeof(UserAuthContext))]
    partial class UserAuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Awful.Database.Context.UserAuth", b =>
                {
                    b.Property<int>("UserAuthId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarLink");

                    b.Property<string>("CookiePath");

                    b.Property<bool>("IsDefaultUser");

                    b.Property<string>("UserName");

                    b.HasKey("UserAuthId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
